User.create!([
  {email: "demo@swappinup.com", password_digest: "$2a$10$bDilSfzJw9Lw7htPPprBX.l49KEgrkfHuYXaGxcMxucSyGUHiWtg2", session_token: "XVYedsBH5ouVHF11hNYyLQ", fname: "Demo", lname: "Man", address: "", phone_number: "123-456-7890"},
  {email: "thedoctor456@yahoo.com", password_digest: "$2a$10$BArH1ThDJkPTsNLc2Tx.oOzeOr4KlGmsAe5GlqTfxl6PeAujAzhIu", session_token: "bFJiJZY8gF8apZX2gjNnYw", fname: "Austin", lname: "Wood", address: "", phone_number: "781-555-9200"},
  {email: "j.p@jefferyplackard.com", password_digest: "$2a$10$p8tncgXrHyYaM49FHK5vouGiJMgUPdXO3cmXApjJi.U6pKVtAH2eO", session_token: "oXbF2SX_KrVhpvIeaTXAxw", fname: "Jeffery", lname: "Plackard", address: "", phone_number: "899-555-1423"},
  {email: "matilda@aol.com", password_digest: "$2a$10$VhQvbK0s3UnKe7LZc5lDBuvGvyttmYEPLwLxwpquL8uv/4JXMC2zy", session_token: "W-dWkrrCh6tjHed-tpstHA", fname: "Matilda", lname: "", address: "", phone_number: ""},
  {email: "pgilbertschmit@gmail.com", password_digest: "$2a$10$p4wm/s7/DY.pU93sZia6B.YuHDDRqCp5ApXIl5fftqWSZN3OJd2qa", session_token: "_19bzcr51VTERxx1CHea-w", fname: "Paul", lname: "Schmit", address: "", phone_number: "561-555-0123"},
  {email: "joey_otool@gmail.com", password_digest: "$2a$10$haZVKn3l1LL/xIohChJKqeroKgQPZJ9FfiDpkGQCRvriQizDBVxFS", session_token: "n0EJUtj4X1TBCAFpPVOB0A", fname: "Joey", lname: "O'Tool", address: "", phone_number: ""},
  {email: "dawgboney@gmail.com", password_digest: "$2a$10$VNMWxVpE.srpFrTkTDukjOs3vnQFEqxGQ.E/rRu3Rs936t3PxeCJK", session_token: "P9WvWUBLhPVU5o6rSRnLsg", fname: "", lname: "", address: "", phone_number: ""},
  {email: "justin.bleck@gmail.com", password_digest: "$2a$10$rxS50RKnG68UZGjo0wkKhe/iWLVUvyuZdeuBNOZAZbi7W0OtDYTQe", session_token: "sAHvcnM_mQnTRJxP944BcA", fname: "Justin", lname: "Bleck", address: "", phone_number: "789-555-4911"},
  {email: "a319b6c@gmail.com", password_digest: "$2a$10$NZd.HYU7mtCjbWr0EGylQOzO4MeptnUt3f.bUbO8l4denO4H0OCWq", session_token: "bnNO1C0OADAvNXDAyXlWMg", fname: "", lname: "", address: "", phone_number: ""},
  {email: "maximumjuice@gmail.com", password_digest: "$2a$10$zwEupi4fGOK8C6Y..FoWvuCc4UpgwGz3l7Qa5bTmfmqiIAi69AJZS", session_token: "fhM_av0k4R3tWARKLNwRAA", fname: "Max", lname: "Juuce", address: "", phone_number: "571-555-9182"}
])
Item.create!([
  {owner_id: 1, name: "Toaster", description: "An old Philips toaster over. Works just fine", photo_url: "v1490370686/vzwsdjvwakzvz0iqyluc.jpg", category: "home_and_living"},
  {owner_id: 1, name: "Bunny Slippers", description: "The coziest slippers I've ever owned", photo_url: "v1490370778/ftpi8yums3d21u6hy5ne.jpg", category: "clothing"},
  {owner_id: 1, name: "Turquoise  fleece jacket", description: "Pretty warm, very cute", photo_url: "v1490371089/jp2rbiag33mguu6g99l1.jpg", category: "clothing"},
  {owner_id: 1, name: "Baseball Cap", description: "Under Armour hat", photo_url: "v1490371288/mvle5abogywfbi6jwejh.jpg", category: "clothing"},
  {owner_id: 2, name: "Copper Saucepot", description: "Pretty old, but very clean and in good condition", photo_url: "v1490371551/xrfudfsbvtkybsmfo5zs.jpg", category: "home_and_living"},
  {owner_id: 2, name: "Dutch Oven", description: "Very clean, good condition dishware", photo_url: "v1490371586/n0de71mgkzivukbelfai.jpg", category: "home_and_living"},
  {owner_id: 2, name: "Cool hat", description: "Pressed fiber sun helmet I found in my dad's garage", photo_url: "v1490371792/rw5st7q0q3rvsfbkgumy.jpg", category: "clothing"},
  {owner_id: 2, name: "JBL Speakers", description: "A little tinny, but good for block parties.", photo_url: "v1490372014/p3cfr9mhac9u6xtu1ggy.jpg", category: "electronics"},
  {owner_id: 2, name: "HP Elitebook", description: "Laptop I've used for a while, still fast for it's age. Running CentOS currently, so no Windows in it.", photo_url: "v1490372086/bz6wngl1pmt1abfymumv.jpg", category: "electronics"},
  {owner_id: 2, name: "Pibow case", description: "Case for Raspberry Pi. Pi not included with case", photo_url: "v1490376174/tsbis4pvwjofgzlrsnax.jpg", category: "electronics"},
  {owner_id: 2, name: "iPhone", description: "White iPhone 5 64GB", photo_url: "v1490376207/lirtonekp04najiqenpk.jpg", category: "electronics"},
  {owner_id: 2, name: "Stool", description: "Green drop stool, very comfy for a piece of plastic", photo_url: "v1490376234/xqm2ad9gue6formcqc8g.jpg", category: "home_and_living"},
  {owner_id: 3, name: "Mens Brown Derby leather shoes", description: "Size 11.5", photo_url: "v1490372270/p8t7xqtfxplbmkywyzpm.jpg", category: "clothing"},
  {owner_id: 3, name: "Large blue fan", description: "Keeps rooms cool", photo_url: "v1490372305/otjkzq3snasgx74wyghy.jpg", category: "home_and_living"},
  {owner_id: 3, name: "Leather Jacket", description: "Older than time, probably. Doesn't fit like it used to. Oh well, from one garage sale to another.", photo_url: "v1490372386/b30snpk3px121udxtwfu.jpg", category: "clothing"},
  {owner_id: 4, name: "Brooch and Earrings", description: "Aquamarine brooch and matching earrings. Please only trade for whole set, they go so nice together", photo_url: "v1490372647/rlvieqsylbztupwslqzz.jpg", category: "jewelry"},
  {owner_id: 4, name: "Labradorite ring", description: "Beautiful ring I found at a flea market", photo_url: "v1490372936/dwsx2bkwh1tzwvtwsgx9.jpg", category: "jewelry"},
  {owner_id: 4, name: "Silver ring", description: "Ring in silver marcasite", photo_url: "v1490372970/wyat2p77fjqk1ko1nzrn.jpg", category: "jewelry"},
  {owner_id: 4, name: "Butterfly pendant", description: "Chain pendant will a butterfly made from rhinestones", photo_url: "v1490373015/pmrqbxpzxhl41iklcueo.jpg", category: "jewelry"},
  {owner_id: 4, name: "Bow earrings", description: "Earrings made in silver marcasite", photo_url: "v1490373047/ln19vmyf6ikimgjdgtn2.jpg", category: "jewelry"},
  {owner_id: 5, name: "Classic iPod", description: "80GB model, no defects or damage", photo_url: "v1490373201/ctyc4ddzplqpszszznxc.jpg", category: "electronics"},
  {owner_id: 5, name: "Neon quilt", description: "I did not make this, my mom gave it to me or something", photo_url: "v1490373316/r9f0m1bksxfchuh2e0vb.jpg", category: "home_and_living"},
  {owner_id: 5, name: "Nintendo gamecube", description: "Sadly, I can't keep this anymore. Still works, game and controller not included", photo_url: "v1490373352/ombnnnjmqcqdqgg7qz7k.jpg", category: "electronics"},
  {owner_id: 5, name: "Nintendo Gamecube controller", description: "Gamecube not included", photo_url: "v1490373379/dohxnb53dufqbo2bztxq.jpg", category: "electronics"},
  {owner_id: 5, name: "Metroid Prime for Gamecube", description: "Gamecube and controller not included", photo_url: "v1490373444/yptxw115hkcausyhwc0m.png", category: "electronics"},
  {owner_id: 5, name: "Pusheen Plushy", description: "13inch dinosaur. Pusheen, you silly cat!", photo_url: "v1490373508/xetrtzfe42fak47xntz8.jpg", category: "kids"},
  {owner_id: 5, name: "Toe shoes", description: "Size 10, most unwanted birthday present of all time", photo_url: "v1490373623/emy41euqdcvt10azqibr.jpg", category: "clothing"},
  {owner_id: 5, name: "Limited Edition original XBox", description: "I can't believe this still works. Hacked, so there's like a hundred games on it. Go nuts", photo_url: "v1490373686/garownq7zojbw66ozhdj.jpg", category: "electronics"},
  {owner_id: 6, name: "Chuck the talking truck", description: "Chuck the talking truck", photo_url: "v1490373781/a6k1zwccsudz9sfeytjz.jpg", category: "kids"},
  {owner_id: 6, name: "Gold baby shoes", description: "gold baby shoes", photo_url: "v1490373822/wfgdh2c179d5n6nwykep.jpg", category: "kids"},
  {owner_id: 6, name: "Gray crib", description: "unused", photo_url: "v1490373841/vw31vqz55kbmmgmvwzuz.jpg", category: "kids"},
  {owner_id: 6, name: "Yellow truck", description: "yellow truck", photo_url: "v1490373918/i6e5hewxrxauvauvct4f.jpg", category: "kids"},
  {owner_id: 6, name: "Toy xylophone", description: "toy xylophone", photo_url: "v1490373942/ilblyhww4qvcq0vtvotm.jpg", category: "kids"},
  {owner_id: 6, name: "Dress", description: "Turquoise prom dress, size 2", photo_url: "v1490376315/gvwlqx4lb9njtzqg6pcr.jpg", category: "clothing"},
  {owner_id: 7, name: "Ipod nano", description: "No songs on it", photo_url: "v1490374084/loplgewxsxl9muzzuuan.jpg", category: "electronics"},
  {owner_id: 7, name: "Mini grill", description: "Don't use inside", photo_url: "v1490374103/w72rkwjl5teybwkjcce2.jpg", category: "home_and_living"},
  {owner_id: 7, name: "Red flannel shirt", description: "size medium", photo_url: "v1490374128/yfs3axmtgrrjxxuxxpig.jpg", category: "clothing"},
  {owner_id: 7, name: "Football jersey", description: "European football. Belonged to simon grech of the sliema wanderers", photo_url: "v1490374220/tgkukcwb8a94zr90vwtw.jpg", category: "clothing"},
  {owner_id: 7, name: "Nerf gun", description: "My cousin's nerf gun", photo_url: "v1490374403/zlq2fx7m1ozv3jtjbmes.jpg", category: "kids"},
  {owner_id: 7, name: "Desk", description: "wooden desk", photo_url: "v1490374481/aeljzz3ddzwve00nxqjd.jpg", category: "home_and_living"},
  {owner_id: 7, name: "Beats by Dre", description: "Don't trade if you don't got something dope", photo_url: "v1490374515/usy5hmfsfesmoo0i34ed.jpg", category: "electronics"},
  {owner_id: 7, name: "CFL Football", description: "American football", photo_url: "v1490374545/hz59twtae3bpicpky0ch.jpg", category: "entertainment"},
  {owner_id: 7, name: "Vans", description: "Vans shoes size 7", photo_url: "v1490374595/w8cmlhjzzxl4vcydypnm.jpg", category: "clothing"},
  {owner_id: 8, name: "Parrot Ziks", description: "headphones", photo_url: "v1490374699/mwrq2qqsxwhceeqfyptv.jpg", category: "electronics"},
  {owner_id: 8, name: "Leupold Porro", description: "9x35 binoculars", photo_url: "v1490374743/zvq5xbaliusw1jbbgzyk.jpg", category: "entertainment"},
  {owner_id: 8, name: "British monopoly set", description: "board game", photo_url: "v1490374766/d3e90fk6tw8jqmc7vi0t.jpg", category: "entertainment"},
  {owner_id: 8, name: "Harry Potter", description: "Full collection of American print", photo_url: "v1490374820/okdscubvvadxpwrbewem.jpg", category: "entertainment"},
  {owner_id: 8, name: "Animorphs", description: "All 54 animorphs, and both alternamorph books", photo_url: "v1490375014/v1xtvzgge7toiell963z.jpg", category: "entertainment"},
  {owner_id: 8, name: "Sorry", description: "Sorry board game. Full game not included. You can blame my cousins", photo_url: "v1490375034/ydfl3aerrohlvbivwqc3.jpg", category: "entertainment"},
  {owner_id: 9, name: "Camera", description: "Pentax", photo_url: "v1490375240/s4dag1tgbqji3rc9apkv.jpg", category: "entertainment"},
  {owner_id: 9, name: "Flight suit", description: "United States coastguard auxiliary flight suit", photo_url: "v1490375293/wsexitvljeiut9yafmws.jpg", category: "clothing"},
  {owner_id: 9, name: "Microwave", description: "Haier microwave 1100W", photo_url: "v1490375377/le7bnrlhffq2kjcnfr1k.jpg", category: "home_and_living"},
  {owner_id: 9, name: "Painting", description: "Larry Greenwalt 1981 original acrylic", photo_url: "v1490375414/qtio9h50ef8qsx4vqxla.jpg", category: "home_and_living"},
  {owner_id: 9, name: "Camera", description: "Canon", photo_url: "v1490375440/wpfsozn1uhtqcdmooetv.jpg", category: "entertainment"},
  {owner_id: 9, name: "Toy horse", description: "Breyer horse", photo_url: "v1490375476/n3jdmm29uxkdrbnmmpbr.jpg", category: "kids"},
  {owner_id: 9, name: "Panini Sandwich press", description: "Not sure where from. Not a George Foreman", photo_url: "v1490375539/hwk3cwh1ehwontwtefum.jpg", category: "home_and_living"},
  {owner_id: 9, name: "Nose ring", description: "Antique Indian nose ring", photo_url: "v1490375628/qdiyku1kvwauj05lsod3.jpg", category: "jewelry"},
  {owner_id: 9, name: "Laptop", description: "Sony Vaio C Series. CD tray stuck, but works otherwise. Runs windows 7", photo_url: "v1490375597/iltww9dl25imalihkio5.jpg", category: "electronics"},
  {owner_id: 10, name: "Barbie doll", description: "Old barbie doll", photo_url: "v1490375760/xneool0dsxg6zuta79bp.jpg", category: "kids"},
  {owner_id: 10, name: "Hot wheels", description: "About 100 total, not all shown", photo_url: "v1490375793/kbsh1i2yaobcncgbhhxd.jpg", category: "kids"},
  {owner_id: 10, name: "Random lego box", description: "Cultivated over many lego sets", photo_url: "v1490375833/uez4ujn2zpxu0zwmn8tj.jpg", category: "kids"},
  {owner_id: 10, name: "Harry Potter", description: "Full Harry Potter bluray set", photo_url: "v1490375856/hcvvjkcleiaiymqnpmlv.jpg", category: "entertainment"},
  {owner_id: 10, name: "Lamborghini Aventator J", description: "Unopened, mint condition hot wheel lamborghini", photo_url: "v1490375925/i6d9zmesbatnwdxpn3er.jpg", category: "entertainment"},
  {owner_id: 10, name: "Goku", description: "SSJ4 Goku non-posable  figure", photo_url: "v1490376006/icwl6aqgy9uay2kzsnqf.jpg", category: "entertainment"},
  {owner_id: 10, name: "Lego set", description: "Unopened, mint condition lego movie \"Creative Ambush\" set. If you know what's good for you, you won't open it.", photo_url: "v1490376057/omn37hjwiepbqjt1zmqs.jpg", category: "entertainment"},
  {owner_id: 10, name: "Mega Charizard", description: "Unopened, mint condition Mega Charizard X", photo_url: "v1490376106/wtkcibcyqlelmg5x6mbp.jpg", category: "entertainment"}
])
Trade.create!([
  {requester_id: 1, receiver_id: 9, request_item_id: 56, offer_item_id: 3, status: "PENDING"},
  {requester_id: 1, receiver_id: 2, request_item_id: 8, offer_item_id: 4, status: "PENDING"},
  {requester_id: 1, receiver_id: 2, request_item_id: 9, offer_item_id: 1, status: "PENDING"},
  {requester_id: 7, receiver_id: 1, request_item_id: 1, offer_item_id: 36, status: "PENDING"},
  {requester_id: 4, receiver_id: 1, request_item_id: 3, offer_item_id: 20, status: "PENDING"},
  {requester_id: 4, receiver_id: 1, request_item_id: 3, offer_item_id: 17, status: "PENDING"}
])